version: '2'

services:
  php:
    image: hitalos/laravel:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - back
  db:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    networks:
      - back
  redis:
    image: redis:latest
    networks:
      - back
    command: redis-server --appendonly yes
  worker:
      image: hitalos/laravel:latest
      command: php artisan queue:work
      volumes:
        - .:/var/www
      networks:
        - back
  websockets:
      image: hitalos/laravel:latest
      command: php artisan websockets:serve
      volumes:
        - .:/var/www
      ports:
        - "6001:6001"
      networks:
        - back

networks:
  back:
    driver: "bridge"

volumes:
  mysqldata:
    driver: "local"
