version: '2'

services:
  php:
    image: hitalos/laravel:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - back
  db:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    networks:
      - back
  queue:
    image: schickling/beanstalkd:latest
    networks:
      - back
  worker:
      image: hitalos/laravel:latest
      command: php artisan queue:work
      volumes:
        - .:/var/www
      networks:
        - back

networks:
  back:
    driver: "bridge"

volumes:
  mysqldata:
    driver: "local"
